# Generated by Django 5.1.5 on 2025-02-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_client_historicalclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalfournisseur',
            name='user',
        ),
    ]
