# Generated by Django 5.1.5 on 2025-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_userext_fournisseur'),
        ('base', '0005_remove_fournisseur_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='fournisseur',
            field=models.ManyToManyField(blank=True, null=True, to='authentification.userext'),
        ),
    ]
