# Generated by Django 5.1.5 on 2025-02-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_fournisseur_fournisseur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='fournisseur',
            new_name='user',
        ),
    ]
