# Generated by Django 5.1.5 on 2025-02-06 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_revendeur_remove_fournisseur_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsite',
            name='revendeur',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.revendeur'),
        ),
        migrations.AddField(
            model_name='site',
            name='revendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.revendeur'),
        ),
    ]
