# Generated by Django 5.1.5 on 2025-02-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_historicalsite_revendeur_site_revendeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='revendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.revendeur'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='revendeur',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.revendeur'),
        ),
    ]
