# Generated by Django 5.1.5 on 2025-02-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_client_user_remove_historicalclient_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='revendeur',
        ),
        migrations.RemoveField(
            model_name='site',
            name='revendeur',
        ),
    ]
