# Generated by Django 5.1.5 on 2025-02-08 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_historicalachats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achats',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 8, 11, 1, 56, 226610)),
        ),
        migrations.AlterField(
            model_name='historicalachats',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 8, 11, 1, 56, 226610)),
        ),
    ]
