# Generated by Django 5.1.5 on 2025-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0002_remove_achats_date_historicalachats'),
    ]

    operations = [
        migrations.AddField(
            model_name='achats',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalachats',
            name='date',
            field=models.DateField(blank=True, default='2025-01-01', editable=False),
            preserve_default=False,
        ),
    ]
