# Generated by Django 5.1.5 on 2025-02-08 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_alter_achats_date_alter_historicalachats_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achats',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 8, 10, 3, 19, 69005, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='historicalachats',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 8, 10, 3, 19, 69005, tzinfo=datetime.timezone.utc)),
        ),
    ]
