# Generated by Django 5.1.5 on 2025-02-08 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0004_alter_achats_date_alter_historicalachats_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achats',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalachats',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
