# Generated by Django 5.1.5 on 2025-02-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0010_remove_client_user_remove_historicalclient_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cin', models.CharField(max_length=15)),
                ('inscription_nombre', models.IntegerField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_debut_travail', models.DateField(blank=True, null=True)),
                ('date_fin_travail', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=255)),
                ('revendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.revendeur')),
            ],
        ),
    ]
