# Generated by Django 5.1.5 on 2025-02-07 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDoeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='depense.personnel')),
            ],
        ),
    ]
