# Generated by Django 5.1.5 on 2025-02-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depense', '0005_divers_historicaldivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divers',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='uploads/divers/proof/'),
        ),
    ]
