# Generated by Django 5.1.5 on 2025-02-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaimentsvente',
            name='paiement_mode',
            field=models.IntegerField(choices=[(1, 'Espéce'), (2, 'Chèque'), (3, 'LCN'), (4, 'Virement')], default=1),
        ),
        migrations.AddField(
            model_name='historicalpaimentsvente',
            name='status',
            field=models.IntegerField(choices=[(1, 'en cours'), (2, 'payé'), (3, 'échec')], default=1),
        ),
        migrations.AddField(
            model_name='paimentsvente',
            name='paiement_mode',
            field=models.IntegerField(choices=[(1, 'Espéce'), (2, 'Chèque'), (3, 'LCN'), (4, 'Virement')], default=1),
        ),
        migrations.AddField(
            model_name='paimentsvente',
            name='status',
            field=models.IntegerField(choices=[(1, 'en cours'), (2, 'payé'), (3, 'échec')], default=1),
        ),
    ]
