# Generated by Django 5.1.5 on 2025-02-06 14:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_client_user_remove_historicalclient_user_and_more'),
        ('paiments', '0002_historicalpaimentsvente_paiement_mode_and_more'),
        ('ventes', '0002_historicalventes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPaimentsVente',
            new_name='HistoricalPaimentByVente',
        ),
        migrations.RenameModel(
            old_name='PaimentsVente',
            new_name='PaimentByVente',
        ),
        migrations.AlterModelOptions(
            name='historicalpaimentbyvente',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical paiment by vente', 'verbose_name_plural': 'historical paiment by ventes'},
        ),
    ]
