# Generated by Django 5.1.5 on 2025-02-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_client_user_remove_historicalclient_user_and_more'),
        ('paiments', '0003_rename_historicalpaimentsvente_historicalpaimentbyvente_and_more'),
        ('ventes', '0002_historicalventes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaimentbyvente',
            old_name='client',
            new_name='client_client',
        ),
        migrations.RemoveField(
            model_name='paimentbyvente',
            name='client',
        ),
        migrations.AddField(
            model_name='historicalpaimentbyvente',
            name='client_vente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.client'),
        ),
        migrations.AddField(
            model_name='paimentbyvente',
            name='client_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_client', to='base.client'),
        ),
        migrations.AddField(
            model_name='paimentbyvente',
            name='client_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_vente', to='base.client'),
        ),
        migrations.AlterField(
            model_name='paimentbyvente',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventes.ventes'),
        ),
    ]
