# Generated by Django 5.1.5 on 2025-02-07 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_client_user_remove_historicalclient_user_and_more'),
        ('paiments', '0004_rename_client_historicalpaimentbyvente_client_client_and_more'),
        ('ventes', '0003_alter_historicalventes_date_alter_ventes_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPaimentByVente',
            new_name='HistoricalPaiment',
        ),
        migrations.RenameModel(
            old_name='PaimentByVente',
            new_name='Paiment',
        ),
        migrations.AlterModelOptions(
            name='historicalpaiment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical paiment', 'verbose_name_plural': 'historical paiments'},
        ),
    ]
