# Generated by Django 5.1.5 on 2025-02-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_client_historicalclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('poids_plateau', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('classe', models.IntegerField(choices=[(1, 'normal'), (2, 'double jaune'), (3, 'blanc'), (4, 'sale'), (5, 'casse'), (6, 'elimine'), (7, 'triage')], default=1)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.batiment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.client')),
            ],
        ),
    ]
