# Generated by Django 5.1.5 on 2025-02-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('base', '0005_remove_fournisseur_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='fournisseur',
            field=models.ManyToManyField(to='base.fournisseur'),
        ),
    ]
