# Generated by Django 5.1.5 on 2025-02-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_userext_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userext',
            name='fournisseur',
        ),
    ]
