# Generated by Django 5.1.5 on 2025-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_historicaluserext_revendeur_userext_fournisseur_and_more'),
        ('base', '0009_historicalsite_revendeur_site_revendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='fournisseur',
            field=models.ManyToManyField(blank=True, to='base.fournisseur'),
        ),
    ]
